name = "GaleX"
grammar = "gale"
path_suffixes = ["gx"]
line_comments = ["//"]
block_comment = ["/* ", " */"]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "<", end = ">", close = false, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "`", end = "`", close = true, newline = false, not_in = ["string", "comment"] },
]
autoclose_before = ";:.,=})]>\" \n\t"
word_characters = ["-"]
tab_size = 2
