//! Integration tests for JS guard validation code generation (Phase 12.3).
//!
//! Tests construct AST nodes directly and verify the generated JavaScript
//! contains expected patterns for client-side validation functions.

use galex::ast::*;
use galex::codegen::emit_form_js;
use galex::codegen::emit_guard_js::{self, GuardJsMeta};
use galex::codegen::js_emitter::JsEmitter;
use galex::codegen::rust_emitter::RustEmitter;
use galex::codegen::CodegenContext;
use galex::span::Span;
use galex::types::ty::TypeInterner;

fn s() -> Span {
    Span::dummy()
}

fn make_guard(name: &str, fields: Vec<GuardFieldDecl>) -> GuardDecl {
    GuardDecl {
        name: name.into(),
        fields,
        span: s(),
    }
}

fn make_field(name: &str, ty: &str, validators: Vec<(&str, Vec<Expr>)>) -> GuardFieldDecl {
    GuardFieldDecl {
        name: name.into(),
        ty: TypeAnnotation::Named {
            name: ty.into(),
            span: s(),
        },
        validators: validators
            .into_iter()
            .map(|(vname, args)| ValidatorCall {
                name: vname.into(),
                args,
                span: s(),
            })
            .collect(),
        span: s(),
    }
}

fn int_lit(val: i64) -> Expr {
    Expr::IntLit {
        value: val,
        span: s(),
    }
}

fn str_lit(val: &str) -> Expr {
    Expr::StringLit {
        value: val.into(),
        span: s(),
    }
}

fn emit_js(decl: &GuardDecl) -> (String, GuardJsMeta) {
    let mut e = JsEmitter::new();
    let meta = emit_guard_js::emit_guard_js_file(&mut e, decl);
    (e.finish(), meta)
}

fn make_program(items: Vec<Item>) -> Program {
    Program { items, span: s() }
}

// ── Integration: full guard → JS ───────────────────────────────────────

#[test]
fn full_login_form_guard() {
    let decl = make_guard(
        "LoginForm",
        vec![
            make_field("email", "string", vec![("trim", vec![]), ("email", vec![])]),
            make_field(
                "password",
                "string",
                vec![("minLen", vec![int_lit(8)]), ("maxLen", vec![int_lit(100)])],
            ),
        ],
    );
    let (out, meta) = emit_js(&decl);

    // File header
    assert!(
        out.contains("Guard validator: `LoginForm`."),
        "should have header: {out}"
    );
    assert!(
        out.contains("Generated by GaleX compiler"),
        "should have gen notice: {out}"
    );

    // Email regex constant
    assert!(
        out.contains("const EMAIL_RE = /^"),
        "should have EMAIL_RE const: {out}"
    );

    // Sanitize function (trim exists)
    assert!(
        out.contains("export function sanitizeLoginForm(data)"),
        "should have sanitize fn: {out}"
    );
    assert!(
        out.contains("out.email = out.email.trim()"),
        "should trim email: {out}"
    );

    // Validate function
    assert!(
        out.contains("export function validateLoginForm(data)"),
        "should have validate fn: {out}"
    );
    assert!(
        out.contains("!EMAIL_RE.test(data.email)"),
        "should check email format: {out}"
    );
    assert!(
        out.contains("data.password.length < 8"),
        "should check minLen: {out}"
    );
    assert!(
        out.contains("data.password.length > 100"),
        "should check maxLen: {out}"
    );

    // Return structure
    assert!(
        out.contains("return errors.length === 0"),
        "should have return: {out}"
    );
    assert!(
        out.contains("{ ok: true, data }"),
        "should return ok on success: {out}"
    );
    assert!(
        out.contains("{ ok: false, errors }"),
        "should return errors on failure: {out}"
    );

    // Meta
    assert_eq!(meta.guard_name, "LoginForm");
    assert_eq!(meta.module_name, "login_form");
    assert_eq!(meta.validate_fn, "validateLoginForm");
    assert_eq!(meta.sanitize_fn.as_deref(), Some("sanitizeLoginForm"));
    assert_eq!(meta.fields, vec!["email", "password"]);
}

#[test]
fn guard_with_all_numeric_validators() {
    let decl = make_guard(
        "NumericForm",
        vec![
            make_field(
                "age",
                "int",
                vec![("min", vec![int_lit(0)]), ("max", vec![int_lit(150)])],
            ),
            make_field(
                "score",
                "float",
                vec![("range", vec![int_lit(0), int_lit(100)])],
            ),
            make_field("count", "int", vec![("positive", vec![])]),
            make_field("balance", "float", vec![("nonNegative", vec![])]),
            make_field("qty", "float", vec![("integer", vec![])]),
        ],
    );
    let (out, _) = emit_js(&decl);

    assert!(out.contains("data.age < 0"), "min(0): {out}");
    assert!(out.contains("data.age > 150"), "max(150): {out}");
    assert!(
        out.contains("data.score < 0 || data.score > 100"),
        "range(0,100): {out}"
    );
    assert!(out.contains("data.count <= 0"), "positive: {out}");
    assert!(out.contains("data.balance < 0"), "nonNegative: {out}");
    assert!(
        out.contains("!Number.isInteger(data.qty)"),
        "integer: {out}"
    );
}

#[test]
fn guard_with_all_string_validators() {
    let decl = make_guard(
        "StringForm",
        vec![
            make_field("name", "string", vec![("minLen", vec![int_lit(2)])]),
            make_field("bio", "string", vec![("maxLen", vec![int_lit(500)])]),
            make_field("title", "string", vec![("nonEmpty", vec![])]),
            make_field("email", "string", vec![("email", vec![])]),
            make_field("website", "string", vec![("url", vec![])]),
            make_field("token", "string", vec![("uuid", vec![])]),
            make_field(
                "role",
                "string",
                vec![("oneOf", vec![str_lit("admin"), str_lit("user")])],
            ),
            make_field(
                "code",
                "string",
                vec![("regex", vec![str_lit(r"^[A-Z]+$")])],
            ),
        ],
    );
    let (out, _) = emit_js(&decl);

    assert!(out.contains("data.name.length < 2"), "minLen: {out}");
    assert!(out.contains("data.bio.length > 500"), "maxLen: {out}");
    assert!(out.contains("data.title.length === 0"), "nonEmpty: {out}");
    assert!(out.contains("!EMAIL_RE.test(data.email)"), "email: {out}");
    assert!(out.contains("!URL_RE.test(data.website)"), "url: {out}");
    assert!(out.contains("!UUID_RE.test(data.token)"), "uuid: {out}");
    assert!(
        out.contains(r#"!["admin", "user"].includes(data.role)"#),
        "oneOf: {out}"
    );
    assert!(out.contains(".test(data.code)"), "regex: {out}");
}

#[test]
fn guard_optional_fields_wrapped_in_null_check() {
    let decl = make_guard(
        "G",
        vec![
            make_field(
                "bio",
                "string",
                vec![("optional", vec![]), ("maxLen", vec![int_lit(500)])],
            ),
            make_field(
                "note",
                "string",
                vec![("nullable", vec![]), ("minLen", vec![int_lit(1)])],
            ),
        ],
    );
    let (out, _) = emit_js(&decl);

    assert!(
        out.contains("if (data.bio != null)"),
        "optional wrapping: {out}"
    );
    assert!(
        out.contains("if (data.note != null)"),
        "nullable wrapping: {out}"
    );
}

#[test]
fn guard_sanitize_trim_and_precision() {
    let decl = make_guard(
        "G",
        vec![
            make_field("name", "string", vec![("trim", vec![])]),
            make_field("price", "float", vec![("precision", vec![int_lit(2)])]),
        ],
    );
    let (out, meta) = emit_js(&decl);

    assert!(
        out.contains("export function sanitizeG(data)"),
        "sanitize fn: {out}"
    );
    assert!(
        out.contains("const out = { ...data }"),
        "shallow clone: {out}"
    );
    assert!(out.contains("out.name = out.name.trim()"), "trim: {out}");
    assert!(
        out.contains("Math.round(out.price * 100) / 100"),
        "precision(2): {out}"
    );
    assert!(out.contains("return out;"), "returns sanitized data: {out}");
    assert!(meta.sanitize_fn.is_some());
}

#[test]
fn guard_no_sanitize_when_no_transforms() {
    let decl = make_guard(
        "G",
        vec![make_field("x", "int", vec![("min", vec![int_lit(0)])])],
    );
    let (out, meta) = emit_js(&decl);

    assert!(!out.contains("sanitize"), "should not have sanitize: {out}");
    assert!(meta.sanitize_fn.is_none());
}

#[test]
fn guard_custom_validator_emits_callback() {
    let decl = make_guard(
        "G",
        vec![make_field(
            "code",
            "string",
            vec![("custom", vec![str_lit("checkCode")])],
        )],
    );
    let (out, _) = emit_js(&decl);

    assert!(
        out.contains("window.__galeValidators?.checkCode?.(data.code) === false"),
        "custom callback: {out}"
    );
    assert!(
        out.contains("failed validation: checkCode"),
        "custom error msg: {out}"
    );
}

#[test]
fn guard_regex_deduplication() {
    let decl = make_guard(
        "G",
        vec![
            make_field("e1", "string", vec![("email", vec![])]),
            make_field("e2", "string", vec![("email", vec![])]),
            make_field("u1", "string", vec![("url", vec![])]),
        ],
    );
    let (out, _) = emit_js(&decl);

    assert_eq!(
        out.matches("const EMAIL_RE").count(),
        1,
        "EMAIL_RE should appear once: {out}"
    );
    assert_eq!(
        out.matches("const URL_RE").count(),
        1,
        "URL_RE should appear once: {out}"
    );
}

#[test]
fn guard_error_messages_match_rust_side() {
    // Verify that JS error messages are identical to Rust-side messages
    let decl = make_guard(
        "G",
        vec![
            make_field("a", "int", vec![("min", vec![int_lit(5)])]),
            make_field("b", "int", vec![("max", vec![int_lit(100)])]),
            make_field("c", "int", vec![("range", vec![int_lit(1), int_lit(10)])]),
            make_field("d", "string", vec![("minLen", vec![int_lit(3)])]),
            make_field("e", "string", vec![("maxLen", vec![int_lit(50)])]),
            make_field("f", "string", vec![("email", vec![])]),
            make_field("g", "string", vec![("url", vec![])]),
            make_field("h", "string", vec![("uuid", vec![])]),
            make_field("i", "string", vec![("nonEmpty", vec![])]),
            make_field("j", "int", vec![("positive", vec![])]),
            make_field("k", "float", vec![("nonNegative", vec![])]),
            make_field("l", "float", vec![("integer", vec![])]),
        ],
    );
    let (out, _) = emit_js(&decl);

    let expected_messages = [
        "must be at least 5",
        "must be at most 100",
        "must be between 1 and 10",
        "must be at least 3 character(s)",
        "must be at most 50 character(s)",
        "must be a valid email address",
        "must be a valid URL",
        "must be a valid UUID",
        "must not be empty",
        "must be positive",
        "must not be negative",
        "must be a whole number",
    ];
    for msg in &expected_messages {
        assert!(out.contains(msg), "missing message '{msg}': {out}");
    }
}

#[test]
fn empty_guard_produces_valid_js() {
    let decl = make_guard("Empty", vec![]);
    let (out, meta) = emit_js(&decl);

    assert!(out.contains("export function validateEmpty(data)"));
    assert!(out.contains("const errors = [];"));
    assert!(out.contains("return errors.length === 0"));
    assert!(meta.fields.is_empty());
}

// ── CodegenContext integration ──────────────────────────────────────────

#[test]
fn codegen_emits_js_guard_files() {
    let interner = TypeInterner::new();
    let program = make_program(vec![Item::GuardDecl(make_guard(
        "LoginForm",
        vec![
            make_field("email", "string", vec![("email", vec![])]),
            make_field("password", "string", vec![("minLen", vec![int_lit(8)])]),
        ],
    ))]);
    let mut ctx = CodegenContext::new(&interner, "test_app");
    ctx.emit_program(&program);

    // Rust guard file should exist
    assert!(
        ctx.files.contains("src/guards/login_form.rs"),
        "should have Rust guard file"
    );
    // JS guard file should exist
    assert!(
        ctx.files.contains("static/js/guards/login_form.js"),
        "should have JS guard file"
    );
    // gale-forms.js runtime should exist
    assert!(
        ctx.files.contains("static/js/gale-forms.js"),
        "should have gale-forms.js runtime"
    );
}

#[test]
fn codegen_js_guard_file_has_correct_content() {
    let interner = TypeInterner::new();
    let program = make_program(vec![Item::GuardDecl(make_guard(
        "SignUp",
        vec![
            make_field(
                "name",
                "string",
                vec![("trim", vec![]), ("minLen", vec![int_lit(1)])],
            ),
            make_field("age", "int", vec![("min", vec![int_lit(18)])]),
        ],
    ))]);
    let mut ctx = CodegenContext::new(&interner, "test_app");
    ctx.emit_program(&program);

    let js = ctx.files.get("static/js/guards/sign_up.js").unwrap();
    assert!(
        js.contains("export function validateSignUp(data)"),
        "validate fn: {js}"
    );
    assert!(
        js.contains("export function sanitizeSignUp(data)"),
        "sanitize fn: {js}"
    );
    assert!(js.contains("data.name.length < 1"), "minLen check: {js}");
    assert!(js.contains("data.age < 18"), "min check: {js}");
}

#[test]
fn codegen_no_gale_forms_without_guards() {
    let interner = TypeInterner::new();
    let program = make_program(vec![Item::ActionDecl(ActionDecl {
        name: "doSomething".into(),
        params: vec![],
        ret_ty: None,
        body: Block {
            stmts: vec![],
            span: s(),
        },
        span: s(),
    })]);
    let mut ctx = CodegenContext::new(&interner, "test_app");
    ctx.emit_program(&program);

    assert!(
        !ctx.files.contains("static/js/gale-forms.js"),
        "gale-forms.js should not exist without guards"
    );
}

#[test]
fn codegen_shared_guard_emits_both_rust_and_js() {
    let interner = TypeInterner::new();
    let guard = make_guard(
        "SharedInput",
        vec![make_field("value", "string", vec![("nonEmpty", vec![])])],
    );
    let program = make_program(vec![Item::SharedBlock(BoundaryBlock {
        items: vec![Item::GuardDecl(guard)],
        span: s(),
    })]);
    let mut ctx = CodegenContext::new(&interner, "test_app");
    ctx.emit_program(&program);

    // Both Rust and JS files should be generated
    assert!(
        ctx.files.contains("src/guards/shared_input.rs"),
        "Rust guard file"
    );
    assert!(
        ctx.files.contains("static/js/guards/shared_input.js"),
        "JS guard file"
    );

    // Verify JS content
    let js = ctx.files.get("static/js/guards/shared_input.js").unwrap();
    assert!(
        js.contains("export function validateSharedInput(data)"),
        "shared guard JS: {js}"
    );
}

#[test]
fn codegen_multiple_guards_emit_multiple_js_files() {
    let interner = TypeInterner::new();
    let program = make_program(vec![
        Item::GuardDecl(make_guard(
            "FormA",
            vec![make_field("x", "int", vec![("min", vec![int_lit(0)])])],
        )),
        Item::GuardDecl(make_guard(
            "FormB",
            vec![make_field("y", "string", vec![("email", vec![])])],
        )),
    ]);
    let mut ctx = CodegenContext::new(&interner, "test_app");
    ctx.emit_program(&program);

    assert!(ctx.files.contains("static/js/guards/form_a.js"));
    assert!(ctx.files.contains("static/js/guards/form_b.js"));
}

// ── Form runtime tests ─────────────────────────────────────────────────

#[test]
fn gale_forms_runtime_is_valid_js() {
    let runtime = emit_form_js::emit_gale_forms_runtime();

    // Should be a complete, self-contained module
    assert!(runtime.contains("export function wireForm"));
    assert!(runtime.contains("function getFormData"));
    assert!(runtime.contains("function clearErrors"));
    assert!(runtime.contains("function showErrors"));
    assert!(runtime.contains("function showFieldError"));

    // Should handle both blur and submit events
    assert!(runtime.contains("'blur'"));
    assert!(runtime.contains("'submit'"));

    // Should reference data-gale-error elements
    assert!(runtime.contains("data-gale-error"));

    // Should call preventDefault on validation failure
    assert!(runtime.contains("e.preventDefault()"));
}

// ── SSR form wiring integration ────────────────────────────────────────

#[test]
fn ssr_form_guard_emits_data_attribute() {
    use galex::codegen::hydration::HydrationCtx;
    use galex::codegen::ssr;

    let mut e = RustEmitter::new();
    let mut h = HydrationCtx::new();
    let nodes = vec![TemplateNode::Element {
        tag: "form".into(),
        attributes: vec![],
        directives: vec![
            Directive::FormAction {
                action: Expr::Ident {
                    name: "login".into(),
                    span: s(),
                },
                span: s(),
            },
            Directive::FormGuard {
                guard: Expr::Ident {
                    name: "LoginForm".into(),
                    span: s(),
                },
                span: s(),
            },
        ],
        children: vec![],
        span: s(),
    }];
    ssr::emit_template_nodes(&mut e, &nodes, &mut h, None);
    let output = e.finish();

    // Should have data-gale-guard attribute on the form
    assert!(
        output.contains("data-gale-guard=\\\"LoginForm\\\""),
        "data-gale-guard attr: {output}"
    );
    // Should still have hidden input for server-side
    assert!(output.contains("__guard"), "hidden input: {output}");
    // Should have wiring script
    assert!(
        output.contains("script type=\\\"module\\\""),
        "wiring script: {output}"
    );
    assert!(
        output.contains("validateLoginForm"),
        "validate fn import: {output}"
    );
    assert!(output.contains("gale-forms.js"), "runtime import: {output}");
}

#[test]
fn ssr_form_error_emits_after_tag_close() {
    use galex::codegen::hydration::HydrationCtx;
    use galex::codegen::ssr;

    let mut e = RustEmitter::new();
    let mut h = HydrationCtx::new();
    let nodes = vec![TemplateNode::Element {
        tag: "div".into(),
        attributes: vec![],
        directives: vec![Directive::FormError {
            field: "email".into(),
            span: s(),
        }],
        children: vec![],
        span: s(),
    }];
    ssr::emit_template_nodes(&mut e, &nodes, &mut h, None);
    let output = e.finish();

    // The data-gale-error div should be emitted after the element's closing >
    assert!(
        output.contains("data-gale-error=\\\"email\\\""),
        "error element: {output}"
    );
}

// ── Guard metadata lookup ──────────────────────────────────────────────

#[test]
fn codegen_find_js_guard_meta() {
    let interner = TypeInterner::new();
    let program = make_program(vec![Item::GuardDecl(make_guard(
        "TestGuard",
        vec![
            make_field(
                "name",
                "string",
                vec![("trim", vec![]), ("minLen", vec![int_lit(1)])],
            ),
            make_field("age", "int", vec![("min", vec![int_lit(0)])]),
        ],
    ))]);
    let mut ctx = CodegenContext::new(&interner, "test_app");
    ctx.emit_program(&program);

    let meta = ctx.find_js_guard_meta("TestGuard");
    assert!(meta.is_some(), "should find guard meta");
    let meta = meta.unwrap();
    assert_eq!(meta.validate_fn, "validateTestGuard");
    assert_eq!(meta.sanitize_fn.as_deref(), Some("sanitizeTestGuard"));
    assert_eq!(meta.fields, vec!["name", "age"]);

    assert!(
        ctx.find_js_guard_meta("NonExistent").is_none(),
        "should return None for unknown guard"
    );
}
