//! Client-side runtime generator — `static/js/__gx/runtime.js`.
//!
//! Produces the shared ESM runtime used by generated action stubs and
//! per-page hydration scripts. The output is invariant (not derived from
//! the AST) — it provides:
//!
//! - **Error classes**: `GaleValidationError`, `GaleServerError`, `GaleNetworkError`
//! - **Fetch wrapper**: `__gx_fetch(actionName, body)` — handles POST, error
//!   classification, and JSON (de)serialization
//! - **Query cache**: `GaleQueryCache` with `mutate()` / `rollback()` /
//!   `invalidate()` for optimistic updates
//! - **Singleton**: `export const queryCache = new GaleQueryCache()`
//! - **Reactive primitives**: `signal`, `derive`, `effect`, `watch`, `batch`
//! - **Hydration utilities**: `hydrate`, `bind`, `$`, `_readData`, `_readEnv`
//! - **Template dynamics**: `replaceRegion` (when blocks), `reconcileList` (each blocks)

/// Generate the complete `static/js/__gx/runtime.js` file contents.
///
/// This is a static string — it does not depend on the user's program.
pub fn generate_runtime_js() -> String {
    r#"// GaleX action runtime — error classes, fetch wrapper, query cache.
// Generated by GaleX compiler — do not edit manually.

// ── Error Classes ──────────────────────────────────────────────────────

/**
 * Thrown when client-side or server-side guard validation fails.
 *
 * `errors` is an array of `{ field: string, message: string }` objects
 * matching the server's `ValidationError` shape.
 */
export class GaleValidationError extends Error {
  constructor(action, errors) {
    super('Validation failed for action \'' + action + '\'');
    this.name = 'GaleValidationError';
    this.action = action;
    this.errors = errors;
  }
}

/**
 * Thrown when the server returns a non-2xx status that is not a
 * validation error (e.g. 500 Internal Server Error, 404, 403).
 */
export class GaleServerError extends Error {
  constructor(action, status, body) {
    super('Server error ' + status + ' for action \'' + action + '\'');
    this.name = 'GaleServerError';
    this.action = action;
    this.status = status;
    this.body = body;
  }
}

/**
 * Thrown when the `fetch()` call itself fails (DNS, timeout, offline).
 */
export class GaleNetworkError extends Error {
  constructor(action, cause) {
    super('Network error for action \'' + action + '\'');
    this.name = 'GaleNetworkError';
    this.action = action;
    this.cause = cause;
  }
}

// ── Fetch Wrapper ──────────────────────────────────────────────────────

/**
 * Internal POST helper for action endpoints.
 *
 * @param {string} actionName  The action identifier (matches the server route).
 * @param {*}      [body]      Arguments to serialize as JSON (omit for no-arg actions).
 * @returns {Promise<*>}       Parsed JSON response body.
 * @throws {GaleNetworkError}     On fetch failure.
 * @throws {GaleValidationError}  On 400 + `validation_failed` response.
 * @throws {GaleServerError}      On any other non-2xx response.
 */
export async function __gx_fetch(actionName, body) {
  var response;
  try {
    response = await fetch('/api/__gx/actions/' + actionName, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: body !== undefined ? JSON.stringify(body) : undefined
    });
  } catch (err) {
    throw new GaleNetworkError(actionName, err);
  }

  if (!response.ok) {
    var responseBody;
    try {
      responseBody = await response.json();
    } catch (_e) {
      responseBody = null;
    }
    if (response.status === 400 && responseBody && responseBody.error === 'validation_failed') {
      throw new GaleValidationError(actionName, responseBody.details);
    }
    throw new GaleServerError(actionName, response.status, responseBody);
  }

  return response.json();
}

// ── Query Cache ────────────────────────────────────────────────────────

/**
 * Reactive query cache supporting optimistic updates, rollback, and
 * invalidation (re-fetch).
 *
 * Usage from action stubs:
 * ```js
 * const addOptimistic = addItem.withMutate('items', function(prev) {
 *   return prev.concat(newItem);
 * });
 * await addOptimistic(newItem);
 * ```
 */
export function GaleQueryCache() {
  this._cache = new Map();
  this._subscribers = new Map();
  this._fetchers = new Map();
}

/**
 * Register a named query and its fetcher function.
 *
 * @param {string}   name     Query identifier.
 * @param {function} fetcher  Async function that returns fresh data.
 */
GaleQueryCache.prototype.register = function(name, fetcher) {
  this._fetchers.set(name, fetcher);
};

/**
 * Fetch fresh data for a query, update the cache, and notify subscribers.
 *
 * @param   {string} name  Query identifier.
 * @param   {...*}   args  Arguments forwarded to the registered fetcher.
 * @returns {Promise<*>}   The fresh data.
 */
GaleQueryCache.prototype.fetch = function(name) {
  var fetcher = this._fetchers.get(name);
  if (!fetcher) throw new Error('Unknown query: ' + name);
  var args = Array.prototype.slice.call(arguments, 1);
  var key = name + ':' + JSON.stringify(args);
  var self = this;
  return fetcher.apply(null, args).then(function(data) {
    self._cache.set(key, { data: data, timestamp: Date.now() });
    self._notify(name, key, data);
    return data;
  });
};

/**
 * Synchronously read cached data (returns `null` on cache miss).
 */
GaleQueryCache.prototype.get = function(name) {
  var args = Array.prototype.slice.call(arguments, 1);
  var key = name + ':' + JSON.stringify(args);
  var entry = this._cache.get(key);
  return entry ? entry.data : null;
};

/**
 * Subscribe to updates for a query name. The callback fires whenever
 * data changes (fetch, mutate, or rollback).
 *
 * @param   {string}   name      Query identifier.
 * @param   {function} callback  `function(data) {}`
 * @returns {function}           Unsubscribe function.
 */
GaleQueryCache.prototype.subscribe = function(name, callback) {
  if (!this._subscribers.has(name)) {
    this._subscribers.set(name, new Set());
  }
  this._subscribers.get(name).add(callback);
  var subs = this._subscribers;
  return function() {
    var set = subs.get(name);
    if (set) set.delete(callback);
  };
};

/**
 * Optimistically update all cache entries for a query.
 *
 * Stores the previous data as `_rollback` so it can be restored on
 * failure via `rollback()`.
 *
 * @param {string}          name     Query identifier.
 * @param {function|*}      updater  A function `function(prev) { return next; }`,
 *                                   or a direct value to set.
 */
GaleQueryCache.prototype.mutate = function(name, updater) {
  var prefix = name + ':';
  for (var entry of this._cache) {
    var key = entry[0];
    var val = entry[1];
    if (key.indexOf(prefix) === 0) {
      var prev = val.data;
      var next = typeof updater === 'function' ? updater(prev) : updater;
      val._rollback = prev;
      val.data = next;
      this._notify(name, key, next);
    }
  }
};

/**
 * Roll back all optimistic mutations for a query, restoring the
 * previous cached data.
 */
GaleQueryCache.prototype.rollback = function(name) {
  var prefix = name + ':';
  for (var entry of this._cache) {
    var key = entry[0];
    var val = entry[1];
    if (key.indexOf(prefix) === 0 && val._rollback !== undefined) {
      val.data = val._rollback;
      delete val._rollback;
      this._notify(name, key, val.data);
    }
  }
};

/**
 * Invalidate (re-fetch) all cache entries for a query.
 *
 * Called automatically after a successful `.withMutate()` action to
 * replace optimistic data with the server's authoritative response.
 */
GaleQueryCache.prototype.invalidate = function(name) {
  var prefix = name + ':';
  var self = this;
  for (var entry of this._cache) {
    var key = entry[0];
    if (key.indexOf(prefix) === 0) {
      var argsJson = key.slice(prefix.length);
      var args;
      try { args = JSON.parse(argsJson); } catch (_e) { args = []; }
      self.fetch.apply(self, [name].concat(args));
    }
  }
};

/** @private Notify subscribers for a query name. */
GaleQueryCache.prototype._notify = function(name, _key, data) {
  var subs = this._subscribers.get(name);
  if (subs) {
    subs.forEach(function(cb) { cb(data); });
  }
};

/** Singleton query cache instance. */
export var queryCache = new GaleQueryCache();

// ── Reactive Primitives ───────────────────────────────────────────────

var _currentSubscriber = null;
var _batchDepth = 0;
var _pendingEffects = new Set();

/**
 * Create a reactive signal — a getter/setter pair with automatic
 * subscriber tracking.
 *
 * @param {*} initial  The initial value.
 * @returns {{ get(): *, set(v: *): void, peek(): *, subscribe(fn): function }}
 */
export function signal(initial) {
  var value = initial;
  var subscribers = new Set();
  return {
    get: function() {
      if (_currentSubscriber) subscribers.add(_currentSubscriber);
      return value;
    },
    set: function(next) {
      if (value === next) return;
      value = next;
      var subs = Array.from(subscribers);
      for (var i = 0; i < subs.length; i++) {
        if (_batchDepth > 0) { _pendingEffects.add(subs[i]); }
        else { subs[i](); }
      }
    },
    peek: function() { return value; },
    subscribe: function(fn) {
      subscribers.add(fn);
      return function() { subscribers.delete(fn); };
    }
  };
}

/**
 * Create a derived value — a cached computation that auto-tracks its
 * signal dependencies and recomputes only when they change.
 *
 * @param {function} fn  The computation function.
 * @returns {{ get(): *, peek(): * }}
 */
export function derive(fn) {
  var cached;
  var dirty = true;
  var subscribers = new Set();

  var invalidate = function() {
    dirty = true;
    var subs = Array.from(subscribers);
    for (var i = 0; i < subs.length; i++) {
      if (_batchDepth > 0) { _pendingEffects.add(subs[i]); }
      else { subs[i](); }
    }
  };

  var recompute = function() {
    var prev = _currentSubscriber;
    _currentSubscriber = invalidate;
    try {
      var next = fn();
      if (next !== cached) {
        cached = next;
        var subs = Array.from(subscribers);
        for (var i = 0; i < subs.length; i++) {
          if (_batchDepth > 0) { _pendingEffects.add(subs[i]); }
          else { subs[i](); }
        }
      }
    } finally { _currentSubscriber = prev; }
    dirty = false;
  };

  recompute();

  return {
    get: function() {
      if (_currentSubscriber) subscribers.add(_currentSubscriber);
      if (dirty) recompute();
      return cached;
    },
    peek: function() {
      if (dirty) recompute();
      return cached;
    }
  };
}

/**
 * Run a side-effect function that auto-tracks signal/derive reads.
 * Re-runs whenever tracked dependencies change.
 *
 * If the function returns a function, it is treated as a cleanup
 * callback and called before the next execution or on dispose.
 *
 * @param {function} fn  The effect body.
 * @returns {function}   Dispose function.
 */
export function effect(fn) {
  var cleanupFn = null;
  var run = function() {
    if (typeof cleanupFn === 'function') { cleanupFn(); cleanupFn = null; }
    var prev = _currentSubscriber;
    _currentSubscriber = run;
    try {
      var result = fn();
      if (typeof result === 'function') cleanupFn = result;
    } finally { _currentSubscriber = prev; }
  };
  run();
  return function() {
    if (typeof cleanupFn === 'function') { cleanupFn(); cleanupFn = null; }
  };
}

/**
 * Watch a specific expression and call back when its value changes.
 *
 * Unlike `effect`, the callback only fires when the watched value
 * actually changes, and receives both the new and previous values.
 *
 * @param {function} sourceFn  Expression to watch (auto-tracked).
 * @param {function} callback  `(next, prev) => void`
 * @returns {function}         Dispose function.
 */
export function watch(sourceFn, callback) {
  var prevValue = sourceFn();
  return effect(function() {
    var next = sourceFn();
    if (next !== prevValue) {
      var prev = prevValue;
      prevValue = next;
      callback(next, prev);
    }
  });
}

/**
 * Batch multiple signal writes so effects only run once at the end.
 *
 * @param {function} fn  The batch body.
 */
export function batch(fn) {
  _batchDepth++;
  try { fn(); }
  finally {
    _batchDepth--;
    if (_batchDepth === 0) {
      var effects = Array.from(_pendingEffects);
      _pendingEffects.clear();
      for (var i = 0; i < effects.length; i++) { effects[i](); }
    }
  }
}

// ── DOM Utilities ─────────────────────────────────────────────────────

/**
 * Query an element by its hydration marker ID.
 *
 * @param {string|number} id  The `data-gx-id` attribute value.
 * @returns {Element|null}
 */
export function $(id) {
  return document.querySelector('[data-gx-id="' + id + '"]');
}

/**
 * Read the serialized server data embedded in the page.
 *
 * @returns {object}  Parsed JSON from `<script type="gale-data">`.
 */
export function _readData() {
  var el = document.querySelector('script[type="gale-data"]');
  if (!el || !el.textContent) return {};
  try { return JSON.parse(el.textContent); } catch (_e) { return {}; }
}

/**
 * Read public environment variables embedded in the page.
 *
 * @returns {object}  Parsed JSON from `<script type="gale-env">`.
 */
export function _readEnv() {
  var el = document.querySelector('script[type="gale-env"]');
  if (!el || !el.textContent) return {};
  try { return JSON.parse(el.textContent); } catch (_e) { return {}; }
}

/**
 * Two-way binding: syncs a signal to an input element's value.
 *
 * Sets the initial value, listens for `input` events, and sets up
 * an effect to push signal changes back to the DOM.
 *
 * @param {Element} el       The input/select/textarea element.
 * @param {object}  sig      A signal object with `.get()` / `.set()`.
 */
export function bind(el, sig) {
  var tag = el.tagName;
  var type = (el.type || '').toLowerCase();

  if (type === 'checkbox') {
    el.checked = !!sig.get();
    el.addEventListener('input', function() { sig.set(el.checked); });
    effect(function() { el.checked = !!sig.get(); });
  } else if (tag === 'SELECT') {
    el.value = sig.get();
    el.addEventListener('change', function() { sig.set(el.value); });
    effect(function() { el.value = sig.get(); });
  } else if (type === 'number' || type === 'range') {
    el.value = sig.get();
    el.addEventListener('input', function() { sig.set(Number(el.value)); });
    effect(function() { el.value = sig.get(); });
  } else {
    el.value = sig.get() != null ? sig.get() : '';
    el.addEventListener('input', function() { sig.set(el.value); });
    effect(function() { el.value = sig.get() != null ? sig.get() : ''; });
  }
}

/**
 * Set up CSS-class-based enter/leave transitions on an element.
 *
 * @param {Element} el    The target element.
 * @param {string}  kind  Transition name (used as CSS class prefix).
 */
export function transition(el, kind) {
  el.classList.add(kind + '-enter-active');
  requestAnimationFrame(function() {
    el.classList.remove(kind + '-enter-active');
  });
}

/**
 * Hydrate SSR-rendered elements using a map of hydration instructions.
 *
 * Each key is a `data-gx-id` value; each value is a function that
 * receives the matched DOM element and sets up interactivity.
 *
 * @param {Object<string, function(Element): void>} instructions
 */
export function hydrate(instructions) {
  for (var id in instructions) {
    if (instructions.hasOwnProperty(id)) {
      var el = $(id);
      if (el) instructions[id](el);
    }
  }
}

/**
 * Replace DOM content between two comment markers.
 *
 * Used for reactive `when` blocks. The SSR output contains:
 *   <!--gx-when:N--> ... content ... <!--/gx-when:N-->
 *
 * Removes everything between the markers and inserts the new HTML
 * produced by `renderFn`.
 *
 * @param {number|string} markerId  The when-block marker ID.
 * @param {function}      renderFn  Returns an HTML string for the active branch.
 */
export function replaceRegion(markerId, renderFn) {
  var start = _findComment('gx-when:' + markerId);
  var end = _findComment('/gx-when:' + markerId);
  if (!start || !end) return;

  while (start.nextSibling && start.nextSibling !== end) {
    start.nextSibling.remove();
  }
  var html = renderFn();
  if (html) {
    var tpl = document.createElement('template');
    tpl.innerHTML = html;
    start.parentNode.insertBefore(tpl.content, end);
  }
}

/**
 * Keyed list reconciliation for reactive `each` blocks.
 *
 * The SSR output contains:
 *   <!--gx-each:N--> ... items ... <!--/gx-each:N-->
 *
 * On update, diffs the new items against the current DOM children
 * using the key function, minimizing DOM mutations.
 *
 * @param {number|string} markerId    The each-block marker ID.
 * @param {Array}         items       The current item array.
 * @param {function}      keyFn       `(item, index) => key`
 * @param {function}      renderItem  `(item, index) => htmlString`
 */
export function reconcileList(markerId, items, keyFn, renderItem) {
  var start = _findComment('gx-each:' + markerId);
  var end = _findComment('/gx-each:' + markerId);
  if (!start || !end) return;

  var parent = start.parentNode;

  // Collect existing keyed nodes
  var existingByKey = new Map();
  var node = start.nextSibling;
  while (node && node !== end) {
    var next = node.nextSibling;
    if (node.__gxKey !== undefined) existingByKey.set(node.__gxKey, node);
    node = next;
  }

  // Build new nodes
  var newNodes = [];
  for (var i = 0; i < items.length; i++) {
    var key = keyFn(items[i], i);
    var el = existingByKey.get(key);
    if (el) { existingByKey.delete(key); }
    else {
      var html = renderItem(items[i], i);
      var tpl = document.createElement('template');
      tpl.innerHTML = html;
      el = tpl.content.firstChild;
    }
    if (el) { el.__gxKey = key; newNodes.push(el); }
  }

  // Remove stale nodes
  existingByKey.forEach(function(old) { old.remove(); });

  // Insert in order before end marker
  for (var j = 0; j < newNodes.length; j++) {
    parent.insertBefore(newNodes[j], end);
  }
}

/** @private Find a comment node by its text content. */
function _findComment(text) {
  var walker = document.createTreeWalker(
    document.body, NodeFilter.SHOW_COMMENT, null
  );
  while (walker.nextNode()) {
    if (walker.currentNode.textContent.trim() === text) {
      return walker.currentNode;
    }
  }
  return null;
}
"#
    .to_string()
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn runtime_contains_error_classes() {
        let js = generate_runtime_js();
        assert!(js.contains("export class GaleValidationError extends Error"));
        assert!(js.contains("export class GaleServerError extends Error"));
        assert!(js.contains("export class GaleNetworkError extends Error"));
    }

    #[test]
    fn runtime_contains_fetch_wrapper() {
        let js = generate_runtime_js();
        assert!(js.contains("export async function __gx_fetch(actionName, body)"));
        assert!(js.contains("/api/__gx/actions/"));
        assert!(js.contains("'Content-Type': 'application/json'"));
    }

    #[test]
    fn runtime_fetch_handles_all_error_types() {
        let js = generate_runtime_js();
        assert!(js.contains("GaleNetworkError(actionName, err)"));
        assert!(js.contains("GaleValidationError(actionName, responseBody.details)"));
        assert!(js.contains("GaleServerError(actionName, response.status, responseBody)"));
    }

    #[test]
    fn runtime_fetch_detects_validation_failed() {
        let js = generate_runtime_js();
        assert!(js.contains("response.status === 400"));
        assert!(js.contains("responseBody.error === 'validation_failed'"));
    }

    #[test]
    fn runtime_contains_query_cache() {
        let js = generate_runtime_js();
        assert!(js.contains("export function GaleQueryCache()"));
        assert!(js.contains("GaleQueryCache.prototype.mutate"));
        assert!(js.contains("GaleQueryCache.prototype.rollback"));
        assert!(js.contains("GaleQueryCache.prototype.invalidate"));
        assert!(js.contains("export var queryCache = new GaleQueryCache()"));
    }

    #[test]
    fn runtime_query_cache_has_core_methods() {
        let js = generate_runtime_js();
        assert!(js.contains("GaleQueryCache.prototype.register"));
        assert!(js.contains("GaleQueryCache.prototype.fetch"));
        assert!(js.contains("GaleQueryCache.prototype.get"));
        assert!(js.contains("GaleQueryCache.prototype.subscribe"));
    }

    #[test]
    fn runtime_mutate_stores_rollback() {
        let js = generate_runtime_js();
        assert!(js.contains("val._rollback = prev"));
    }

    #[test]
    fn runtime_rollback_restores_data() {
        let js = generate_runtime_js();
        assert!(js.contains("val.data = val._rollback"));
        assert!(js.contains("delete val._rollback"));
    }

    #[test]
    fn runtime_is_valid_esm() {
        let js = generate_runtime_js();
        // Must only use export (not module.exports / require)
        assert!(!js.contains("module.exports"));
        assert!(!js.contains("require("));
        // Must have at least one export
        assert!(js.contains("export "));
    }

    // ── Reactive primitives ───────────────────────────────────

    #[test]
    fn runtime_contains_signal() {
        let js = generate_runtime_js();
        assert!(js.contains("export function signal(initial)"));
        assert!(js.contains(".get"));
        assert!(js.contains(".set"));
    }

    #[test]
    fn runtime_contains_derive() {
        let js = generate_runtime_js();
        assert!(js.contains("export function derive(fn)"));
    }

    #[test]
    fn runtime_contains_effect() {
        let js = generate_runtime_js();
        assert!(js.contains("export function effect(fn)"));
    }

    #[test]
    fn runtime_contains_watch() {
        let js = generate_runtime_js();
        assert!(js.contains("export function watch(sourceFn, callback)"));
    }

    #[test]
    fn runtime_contains_batch() {
        let js = generate_runtime_js();
        assert!(js.contains("export function batch(fn)"));
    }

    // ── DOM utilities ─────────────────────────────────────────

    #[test]
    fn runtime_contains_dom_selector() {
        let js = generate_runtime_js();
        assert!(js.contains("export function $(id)"));
        assert!(js.contains("data-gx-id"));
    }

    #[test]
    fn runtime_contains_read_data() {
        let js = generate_runtime_js();
        assert!(js.contains("export function _readData()"));
        assert!(js.contains("gale-data"));
    }

    #[test]
    fn runtime_contains_read_env() {
        let js = generate_runtime_js();
        assert!(js.contains("export function _readEnv()"));
        assert!(js.contains("gale-env"));
    }

    #[test]
    fn runtime_contains_bind() {
        let js = generate_runtime_js();
        assert!(js.contains("export function bind(el, sig)"));
        assert!(js.contains("checkbox"));
        assert!(js.contains("addEventListener"));
    }

    #[test]
    fn runtime_contains_hydrate() {
        let js = generate_runtime_js();
        assert!(js.contains("export function hydrate(instructions)"));
    }

    #[test]
    fn runtime_contains_replace_region() {
        let js = generate_runtime_js();
        assert!(js.contains("export function replaceRegion(markerId, renderFn)"));
        assert!(js.contains("gx-when:"));
    }

    #[test]
    fn runtime_contains_reconcile_list() {
        let js = generate_runtime_js();
        assert!(js.contains("export function reconcileList(markerId, items, keyFn, renderItem)"));
        assert!(js.contains("gx-each:"));
    }

    #[test]
    fn runtime_contains_transition() {
        let js = generate_runtime_js();
        assert!(js.contains("export function transition(el, kind)"));
    }
}
