//! Built-in CSS transition class generation.
//!
//! Generates `public/_gale/transitions.css` containing CSS classes for
//! the built-in transition types: fade, slide, scale, blur.
//!
//! Each transition uses a two-phase class pattern:
//! 1. `gale-{type}-enter` — initial state (e.g. `opacity: 0`)
//! 2. `gale-{type}-enter-active` — active state (e.g. `opacity: 1; transition: ...`)
//! 3. `gale-{type}-exit` — start exit (matches the "on" state)
//! 4. `gale-{type}-exit-active` — end exit (e.g. `opacity: 0; transition: ...`)
//!
//! Also includes a `prefers-reduced-motion` override that disables all
//! animation durations for accessibility.

/// Generate the built-in transitions CSS file.
pub fn emit_transitions_css() -> String {
    r#"/* GaleX built-in transitions — generated by GaleX compiler. */

/* ── Fade ───────────────────────────────────────────────────────────── */
.gale-fade-enter {
  opacity: 0;
}
.gale-fade-enter-active {
  opacity: 1;
  transition: opacity 0.3s ease;
}
.gale-fade-exit-active {
  opacity: 0;
  transition: opacity 0.3s ease;
}

/* ── Slide ──────────────────────────────────────────────────────────── */
.gale-slide-enter {
  transform: translateY(-10px);
  opacity: 0;
}
.gale-slide-enter-active {
  transform: translateY(0);
  opacity: 1;
  transition: transform 0.3s ease, opacity 0.3s ease;
}
.gale-slide-exit-active {
  transform: translateY(10px);
  opacity: 0;
  transition: transform 0.3s ease, opacity 0.3s ease;
}

/* ── Scale ──────────────────────────────────────────────────────────── */
.gale-scale-enter {
  transform: scale(0.95);
  opacity: 0;
}
.gale-scale-enter-active {
  transform: scale(1);
  opacity: 1;
  transition: transform 0.3s ease, opacity 0.3s ease;
}
.gale-scale-exit-active {
  transform: scale(0.95);
  opacity: 0;
  transition: transform 0.3s ease, opacity 0.3s ease;
}

/* ── Blur ───────────────────────────────────────────────────────────── */
.gale-blur-enter {
  filter: blur(4px);
  opacity: 0;
}
.gale-blur-enter-active {
  filter: blur(0);
  opacity: 1;
  transition: filter 0.3s ease, opacity 0.3s ease;
}
.gale-blur-exit-active {
  filter: blur(4px);
  opacity: 0;
  transition: filter 0.3s ease, opacity 0.3s ease;
}

/* ── Reduced Motion ─────────────────────────────────────────────────── */
@media (prefers-reduced-motion: reduce) {
  [class*="gale-"][class*="-enter-active"],
  [class*="gale-"][class*="-exit-active"] {
    transition-duration: 0.01ms !important;
    animation-duration: 0.01ms !important;
  }
}
"#
    .to_string()
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn css_contains_all_builtin_transitions() {
        let css = emit_transitions_css();
        for name in &["fade", "slide", "scale", "blur"] {
            assert!(
                css.contains(&format!(".gale-{name}-enter")),
                "missing {name}-enter"
            );
            assert!(
                css.contains(&format!(".gale-{name}-enter-active")),
                "missing {name}-enter-active"
            );
            assert!(
                css.contains(&format!(".gale-{name}-exit-active")),
                "missing {name}-exit-active"
            );
        }
    }

    #[test]
    fn css_has_reduced_motion() {
        let css = emit_transitions_css();
        assert!(css.contains("prefers-reduced-motion: reduce"));
        assert!(css.contains("transition-duration: 0.01ms"));
    }

    #[test]
    fn css_has_header() {
        let css = emit_transitions_css();
        assert!(css.contains("GaleX built-in transitions"));
    }
}
