//! Low-level JavaScript source code emitter with indent tracking.
//!
//! `JsEmitter` accumulates JavaScript source text in a `String` buffer,
//! automatically inserting indentation at line starts. Higher-level
//! helpers produce idiomatic JS constructs (functions, imports, consts).
//!
//! Mirrors [`RustEmitter`](super::rust_emitter::RustEmitter) but uses
//! 2-space indent (JS convention) and JS-specific helpers.

/// A buffered JavaScript source code writer with automatic indentation.
///
/// All output goes through [`write`] or [`writeln`], which prepend the
/// current indent prefix when a new line starts. Structural helpers like
/// [`block`] and [`emit_export_fn`] build on these primitives.
pub struct JsEmitter {
    buf: String,
    indent_level: usize,
    at_line_start: bool,
}

/// Two spaces per indent level (standard JS/Prettier default).
const INDENT: &str = "  ";

impl JsEmitter {
    // ── Construction ───────────────────────────────────────────────

    /// Create a new, empty emitter at indent level 0.
    pub fn new() -> Self {
        Self {
            buf: String::with_capacity(4096),
            indent_level: 0,
            at_line_start: true,
        }
    }

    /// Consume the emitter and return the accumulated source code.
    pub fn finish(self) -> String {
        self.buf
    }

    /// Return a reference to the accumulated buffer (for assertions in tests).
    pub fn as_str(&self) -> &str {
        &self.buf
    }

    // ── Indent control ─────────────────────────────────────────────

    /// Increase the indent level by one.
    pub fn indent(&mut self) {
        self.indent_level += 1;
    }

    /// Decrease the indent level by one (saturating at 0).
    pub fn dedent(&mut self) {
        self.indent_level = self.indent_level.saturating_sub(1);
    }

    // ── Low-level write ────────────────────────────────────────────

    /// Write raw text, inserting the indent prefix if we're at a line start.
    ///
    /// Does **not** append a newline — use [`writeln`] for that.
    pub fn write(&mut self, text: &str) {
        if text.is_empty() {
            return;
        }
        if self.at_line_start {
            for _ in 0..self.indent_level {
                self.buf.push_str(INDENT);
            }
            self.at_line_start = false;
        }
        self.buf.push_str(text);
    }

    /// Write text followed by a newline, auto-indenting at line start.
    pub fn writeln(&mut self, text: &str) {
        self.write(text);
        self.buf.push('\n');
        self.at_line_start = true;
    }

    /// Emit a blank line (no indentation, just `\n`).
    pub fn newline(&mut self) {
        self.buf.push('\n');
        self.at_line_start = true;
    }

    /// Write formatted text followed by a newline.
    pub fn writeln_fmt(&mut self, args: std::fmt::Arguments<'_>) {
        let text = std::fmt::format(args);
        self.writeln(&text);
    }

    // ── Block helpers ──────────────────────────────────────────────

    /// Emit a `header { ... }` block with auto-indent.
    ///
    /// ```text
    /// header {
    ///   <body produced by f>
    /// }
    /// ```
    pub fn block(&mut self, header: &str, f: impl FnOnce(&mut Self)) {
        self.writeln(&format!("{header} {{"));
        self.indent();
        f(self);
        self.dedent();
        self.writeln("}");
    }

    /// Emit a `header { ... }` block, then a blank line after the closing brace.
    pub fn block_with_sep(&mut self, header: &str, f: impl FnOnce(&mut Self)) {
        self.block(header, f);
        self.newline();
    }

    // ── JS-specific helpers ────────────────────────────────────────

    /// Emit a file-level header comment.
    pub fn emit_file_header(&mut self, description: &str) {
        self.writeln(&format!("// {description}"));
        self.writeln("// Generated by GaleX compiler — do not edit manually.");
        self.newline();
    }

    /// Emit a regular comment line (`// text`).
    pub fn emit_comment(&mut self, text: &str) {
        self.writeln(&format!("// {text}"));
    }

    /// Emit an ES module import statement.
    ///
    /// ```text
    /// import { foo, bar } from './path.js';
    /// ```
    pub fn emit_import(&mut self, names: &[&str], from: &str) {
        let joined = names.join(", ");
        self.writeln(&format!("import {{ {joined} }} from '{from}';"));
    }

    /// Emit a `const` declaration.
    ///
    /// ```text
    /// const FOO = value;
    /// ```
    pub fn emit_const(&mut self, name: &str, value: &str) {
        self.writeln(&format!("const {name} = {value};"));
    }

    /// Emit an `export function name(params) { ... }` block.
    pub fn emit_export_fn(&mut self, name: &str, params: &[&str], body: impl FnOnce(&mut Self)) {
        let params_str = params.join(", ");
        self.block(&format!("export function {name}({params_str})"), body);
    }

    /// Emit a `function name(params) { ... }` block (non-exported).
    pub fn emit_fn(&mut self, name: &str, params: &[&str], body: impl FnOnce(&mut Self)) {
        let params_str = params.join(", ");
        self.block(&format!("function {name}({params_str})"), body);
    }

    /// Emit an `if (condition) { ... }` block.
    pub fn emit_if(&mut self, condition: &str, body: impl FnOnce(&mut Self)) {
        self.block(&format!("if ({condition})"), body);
    }

    /// Emit an `if (condition) { ... } else { ... }` construct.
    pub fn emit_if_else(
        &mut self,
        condition: &str,
        if_body: impl FnOnce(&mut Self),
        else_body: impl FnOnce(&mut Self),
    ) {
        self.writeln(&format!("if ({condition}) {{"));
        self.indent();
        if_body(self);
        self.dedent();
        self.writeln("} else {");
        self.indent();
        else_body(self);
        self.dedent();
        self.writeln("}");
    }

    /// Emit a `for (const x of iterable) { ... }` block.
    pub fn emit_for_of(&mut self, binding: &str, iterable: &str, body: impl FnOnce(&mut Self)) {
        self.block(&format!("for (const {binding} of {iterable})"), body);
    }
}

impl Default for JsEmitter {
    fn default() -> Self {
        Self::new()
    }
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_emitter_produces_empty_string() {
        let e = JsEmitter::new();
        assert_eq!(e.finish(), "");
    }

    #[test]
    fn writeln_appends_newline() {
        let mut e = JsEmitter::new();
        e.writeln("const x = 1;");
        assert_eq!(e.finish(), "const x = 1;\n");
    }

    #[test]
    fn indent_produces_two_spaces() {
        let mut e = JsEmitter::new();
        e.indent();
        e.writeln("return true;");
        assert_eq!(e.finish(), "  return true;\n");
    }

    #[test]
    fn nested_indent() {
        let mut e = JsEmitter::new();
        e.indent();
        e.indent();
        e.writeln("deep;");
        assert_eq!(e.finish(), "    deep;\n");
    }

    #[test]
    fn block_auto_indents() {
        let mut e = JsEmitter::new();
        e.block("if (true)", |e| {
            e.writeln("return 1;");
        });
        let out = e.finish();
        assert!(out.contains("if (true) {\n"));
        assert!(out.contains("  return 1;\n"));
        assert!(out.contains("}\n"));
    }

    #[test]
    fn emit_file_header() {
        let mut e = JsEmitter::new();
        e.emit_file_header("Guard validator: `User`.");
        let out = e.finish();
        assert!(out.contains("// Guard validator: `User`."));
        assert!(out.contains("// Generated by GaleX compiler"));
    }

    #[test]
    fn emit_import_single() {
        let mut e = JsEmitter::new();
        e.emit_import(&["wireForm"], "./gale-forms.js");
        assert_eq!(e.finish(), "import { wireForm } from './gale-forms.js';\n");
    }

    #[test]
    fn emit_import_multiple() {
        let mut e = JsEmitter::new();
        e.emit_import(&["validateUser", "sanitizeUser"], "./guards/user.js");
        let out = e.finish();
        assert!(out.contains("import { validateUser, sanitizeUser }"));
    }

    #[test]
    fn emit_const_regex() {
        let mut e = JsEmitter::new();
        e.emit_const("EMAIL_RE", r"/^[^@\s]+@[^@\s]+\.[^@\s]+$/");
        let out = e.finish();
        assert!(out.starts_with("const EMAIL_RE = /^"));
        assert!(out.ends_with("$/;\n"));
    }

    #[test]
    fn emit_export_fn() {
        let mut e = JsEmitter::new();
        e.emit_export_fn("validateUser", &["data"], |e| {
            e.writeln("return { ok: true };");
        });
        let out = e.finish();
        assert!(out.contains("export function validateUser(data) {\n"));
        assert!(out.contains("  return { ok: true };\n"));
    }

    #[test]
    fn emit_if() {
        let mut e = JsEmitter::new();
        e.emit_if("x < 5", |e| {
            e.writeln("errors.push('too small');");
        });
        let out = e.finish();
        assert!(out.contains("if (x < 5) {\n"));
        assert!(out.contains("  errors.push('too small');\n"));
    }

    #[test]
    fn emit_for_of() {
        let mut e = JsEmitter::new();
        e.emit_for_of("field", "fields", |e| {
            e.writeln("check(field);");
        });
        let out = e.finish();
        assert!(out.contains("for (const field of fields) {\n"));
        assert!(out.contains("  check(field);\n"));
    }

    #[test]
    fn dedent_saturates_at_zero() {
        let mut e = JsEmitter::new();
        e.dedent();
        e.dedent();
        e.writeln("no crash;");
        assert_eq!(e.finish(), "no crash;\n");
    }
}
