//! Output project scaffolding — generates the `gale_build/` directory structure.
//!
//! Produces a self-contained Rust/Cargo project that depends on the `gale`
//! library crate for its middleware stack, and adds generated route handlers,
//! guard validators, channel handlers, and shared types.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use super::rust_emitter::RustEmitter;

// ── ProjectFiles ───────────────────────────────────────────────────────

/// Accumulated set of files to write to the output directory.
///
/// Files are stored as `(relative_path, content)` pairs and written
/// atomically via [`write_to_disk`].
pub struct ProjectFiles {
    /// Sorted map from relative path to file content.
    files: BTreeMap<PathBuf, String>,
}

impl ProjectFiles {
    /// Create an empty file set.
    pub fn new() -> Self {
        Self {
            files: BTreeMap::new(),
        }
    }

    /// Register a file to be written.
    ///
    /// `path` is relative to the output directory root (e.g. `src/main.rs`).
    pub fn add_file(&mut self, path: impl Into<PathBuf>, content: String) {
        self.files.insert(path.into(), content);
    }

    /// Return the number of registered files.
    pub fn len(&self) -> usize {
        self.files.len()
    }

    /// Check if no files are registered.
    pub fn is_empty(&self) -> bool {
        self.files.is_empty()
    }

    /// Iterate over all registered files as `(path, content)` pairs.
    pub fn iter(&self) -> impl Iterator<Item = (&Path, &str)> {
        self.files.iter().map(|(p, c)| (p.as_path(), c.as_str()))
    }

    /// Remove a file and re-add it under a new path (for asset hashing).
    pub fn rename(&mut self, old_path: &Path, new_path: &Path) {
        if let Some(content) = self.files.remove(old_path) {
            self.files.insert(new_path.to_path_buf(), content);
        }
    }

    /// Check if a file is registered at the given path.
    pub fn contains(&self, path: &str) -> bool {
        self.files.contains_key(Path::new(path))
    }

    /// Get the content of a registered file.
    pub fn get(&self, path: &str) -> Option<&str> {
        self.files.get(Path::new(path)).map(|s| s.as_str())
    }

    /// Write all registered files to disk under `output_dir`.
    ///
    /// Creates parent directories as needed. Overwrites existing files.
    pub fn write_to_disk(&self, output_dir: &Path) -> std::io::Result<()> {
        for (rel_path, content) in &self.files {
            let full_path = output_dir.join(rel_path);
            if let Some(parent) = full_path.parent() {
                std::fs::create_dir_all(parent)?;
            }

            // Apply minification based on file extension.
            let ext = rel_path.extension().and_then(|e| e.to_str()).unwrap_or("");
            let minified = match ext {
                "js" => crate::minify::js::minify_js(content),
                "css" => crate::minify::css::minify_css(content),
                "rs" => crate::minify::rust::minify_rs(content),
                _ => content.clone(),
            };

            std::fs::write(&full_path, minified)?;
        }
        Ok(())
    }
}

impl Default for ProjectFiles {
    fn default() -> Self {
        Self::new()
    }
}

// ── Static file generators ─────────────────────────────────────────────

/// Generate the `Cargo.toml` for the build output project.
///
/// The generated project depends on the `gale` server crate (via path)
/// for its middleware stack, plus the minimal set of crates needed for
/// the generated handler code.
/// `needs_regex` controls whether the `regex` crate is included (only
/// when guards use regex-based validators like email, url, uuid, or custom regex).
pub fn generate_cargo_toml(project_name: &str, needs_regex: bool, gale_dep: &str) -> String {
    let mut e = RustEmitter::new();
    // Cargo.toml is not Rust code, but the emitter works fine for any
    // indented text format. We use write/writeln directly.
    e.writeln("[package]");
    e.writeln(&format!("name = \"{project_name}\""));
    e.writeln("version = \"0.1.0\"");
    e.writeln("edition = \"2021\"");
    e.writeln("# Generated by GaleX compiler — do not edit manually.");
    e.newline();
    // Standalone workspace — prevents Cargo from looking for a parent workspace
    e.writeln("[workspace]");
    e.newline();
    e.writeln("[dependencies]");
    e.writeln(&format!("gale = {gale_dep}"));
    e.writeln("axum = { version = \"0.8\", features = [\"ws\"] }");
    e.writeln("tokio = { version = \"1\", features = [\"full\"] }");
    e.writeln("serde = { version = \"1\", features = [\"derive\"] }");
    e.writeln("serde_json = \"1\"");
    e.writeln("tower-http = { version = \"0.6\", features = [\"cors\"] }");
    e.writeln("dotenvy = \"0.15\"");
    e.writeln("futures-util = \"0.3\"");
    if needs_regex {
        e.writeln("regex = \"1\"");
    }
    e.newline();
    e.writeln("[profile.release]");
    e.writeln("lto = true");
    e.writeln("codegen-units = 1");
    e.writeln("strip = true");
    e.writeln("panic = \"abort\"");
    e.writeln("opt-level = 3");
    e.finish()
}

/// Generate the `src/main.rs` entry point.
///
/// Includes the tokio runtime, config loading, logging init, and
/// `build_router()` with actual route registrations.
///
/// `action_routes` is a list of `(action_name, module_name)` pairs
/// for registering action POST endpoints.
/// A middleware registration for the router builder.
#[derive(Debug, Clone)]
pub struct MiddlewareRegistration {
    /// Module path to the middleware function: `middleware::auth::middleware_fn`
    pub handler_path: String,
    /// `"global"`, `"prefix:/api"`, or `"resource:Users"`.
    pub target_kind: String,
    /// The path prefix (for segment targeting) or empty.
    pub target_value: String,
}

pub fn generate_main_rs(
    module_names: &MainModules,
    has_layout: bool,
    route_paths: &[(String, String)],
    action_routes: &[(String, String)],
    api_route_groups: &[(String, Vec<(String, String)>)],
    channel_routes: &[(String, String)],
    middleware_regs: &[MiddlewareRegistration],
) -> String {
    let mut e = RustEmitter::new();
    e.emit_file_header("Server entry point.");
    e.newline();

    // Re-export the gale crate under the `gale` name
    // (the crate's lib target is named `gale_lib`)
    e.writeln("extern crate gale_lib as gale;");
    e.newline();

    // Module declarations
    if module_names.has_actions {
        e.writeln("mod actions;");
    }
    if module_names.has_guards {
        e.writeln("mod guards;");
    }
    if module_names.has_channels {
        e.writeln("mod channels;");
    }
    if module_names.has_shared {
        e.writeln("mod shared;");
    }
    if module_names.has_routes {
        e.writeln("mod routes;");
        e.writeln("mod layout;");
        e.writeln("mod gale_ssr;");
    }
    if module_names.has_api {
        e.writeln("mod api;");
    }
    if module_names.has_middleware {
        e.writeln("mod middleware;");
        e.writeln("mod gale_middleware;");
    }
    if module_names.has_env {
        e.writeln("mod env_config;");
    }
    // Asset manifest is always generated (identity map in dev, content-hashed in production)
    e.writeln("mod asset_manifest;");
    let _ = has_layout; // layout.rs is always generated when routes exist
    e.newline();

    // Imports
    e.emit_use("gale::config::Config");
    e.newline();

    // Main function
    e.emit_attribute("tokio::main");
    e.block("async fn main()", |e| {
        if module_names.has_env {
            e.emit_comment("Load .env file and validate environment variables (fail-fast)");
            e.writeln("let _ = &*crate::env_config::ENV;");
            e.newline();
        }
        e.writeln("let config = Config::load();");
        e.writeln("gale::logging::init(&config.logging);");
        e.newline();
        e.writeln("let app = build_router();");
        e.newline();
        e.emit_comment("Delegate to Gale's server infrastructure");
        e.emit_comment("(handles middleware, TLS, graceful shutdown)");
        e.writeln("gale::server::run_with_app(config, app).await;");
    });
    e.newline();

    // Partition middleware by target kind
    let global_mw: Vec<&MiddlewareRegistration> = middleware_regs
        .iter()
        .filter(|m| m.target_kind == "global")
        .collect();
    let segment_mw: Vec<&MiddlewareRegistration> = middleware_regs
        .iter()
        .filter(|m| m.target_kind == "prefix")
        .collect();
    let resource_mw: Vec<&MiddlewareRegistration> = middleware_regs
        .iter()
        .filter(|m| m.target_kind == "resource")
        .collect();

    // Router builder — with actual route registrations and middleware layers
    e.block("fn build_router() -> axum::Router", |e| {
        let has_any = !route_paths.is_empty()
            || !action_routes.is_empty()
            || !api_route_groups.is_empty()
            || !channel_routes.is_empty()
            || !middleware_regs.is_empty();

        // Collect segment prefixes that need nested sub-routers
        let mut segment_prefixes: Vec<&str> = segment_mw
            .iter()
            .map(|m| m.target_value.as_str())
            .collect();
        segment_prefixes.sort();
        segment_prefixes.dedup();

        // Emit nested sub-routers for segment middleware
        for prefix in &segment_prefixes {
            let var_name = prefix
                .trim_start_matches('/')
                .replace(['/', '-'], "_");
            let var_name = format!("{var_name}_router");

            // Collect API routes that fall under this prefix
            let nested_api: Vec<_> = api_route_groups
                .iter()
                .filter(|(path, _)| path.starts_with(prefix))
                .collect();

            e.writeln(&format!("let {var_name} = axum::Router::new()"));
            e.indent();

            // Add API routes under this prefix (strip the prefix)
            for (path, methods) in &nested_api {
                let relative = path.strip_prefix(prefix).unwrap_or(path);
                let relative = if relative.is_empty() { "/" } else { relative };
                if methods.len() == 1 {
                    let (method, handler) = &methods[0];
                    e.writeln(&format!(
                        ".route({relative:?}, axum::routing::{method}({handler}))"
                    ));
                } else {
                    let mut chain = String::new();
                    for (i, (method, handler)) in methods.iter().enumerate() {
                        if i == 0 {
                            chain.push_str(&format!("axum::routing::{method}({handler})"));
                        } else {
                            chain.push_str(&format!(".{method}({handler})"));
                        }
                    }
                    e.writeln(&format!(".route({relative:?}, {chain})"));
                }
            }

            // Apply segment middleware to this sub-router
            for mw in &segment_mw {
                if mw.target_value == *prefix {
                    e.writeln(&format!(
                        ".layer(axum::middleware::from_fn({}))",
                        mw.handler_path
                    ));
                }
            }
            e.writeln(";");
            e.dedent();
            e.newline();
        }

        if !has_any {
            e.writeln("axum::Router::new()");
        } else {
            e.writeln("axum::Router::new()");
            e.indent();

            // Page routes (GET)
            for (path, mod_name) in route_paths {
                // Check for resource-targeted middleware
                e.writeln(&format!(
                    ".route({path:?}, axum::routing::get(routes::{mod_name}::handler))"
                ));
            }

            // JSON page endpoints for client-side navigation
            for (_path, mod_name) in route_paths {
                e.writeln(&format!(
                    ".route(\"/__gx/pages/{mod_name}.json\", axum::routing::get(routes::{mod_name}::json_handler))"
                ));
            }

            // Action endpoints (POST)
            for (action_name, mod_name) in action_routes {
                e.writeln(&format!(
                    ".route(\"/api/__gx/actions/{action_name}\", axum::routing::post(actions::{mod_name}::handler))"
                ));
            }

            // Channel WebSocket endpoints (GET with broadcast state)
            for (channel_name, mod_name) in channel_routes {
                e.writeln(&format!(
                    ".route(\"/ws/__gx/channels/{channel_name}\", axum::routing::get(channels::{mod_name}::handler).with_state(channels::{mod_name}::{channel_name}State::new()))"
                ));
            }

            // API resource routes NOT already nested
            for (path, methods) in api_route_groups {
                let already_nested = segment_prefixes
                    .iter()
                    .any(|prefix| path.starts_with(prefix));
                if already_nested {
                    continue; // These routes are inside a nested sub-router
                }

                if methods.len() == 1 {
                    let (method, handler) = &methods[0];
                    e.writeln(&format!(
                        ".route({path:?}, axum::routing::{method}({handler}))"
                    ));
                } else {
                    let mut chain = String::new();
                    for (i, (method, handler)) in methods.iter().enumerate() {
                        if i == 0 {
                            chain.push_str(&format!("axum::routing::{method}({handler})"));
                        } else {
                            chain.push_str(&format!(".{method}({handler})"));
                        }
                    }
                    e.writeln(&format!(".route({path:?}, {chain})"));
                }
            }

            // Nest segment sub-routers
            for prefix in &segment_prefixes {
                let var_name = prefix
                    .trim_start_matches('/')
                    .replace(['/', '-'], "_");
                let var_name = format!("{var_name}_router");
                e.writeln(&format!(".nest({prefix:?}, {var_name})"));
            }

            // Resource-targeted middleware (applied to specific route groups)
            for mw in &resource_mw {
                e.emit_comment(&format!("Middleware for resource: {}", mw.target_value));
                e.writeln(&format!(
                    ".layer(axum::middleware::from_fn({}))",
                    mw.handler_path
                ));
            }

            // Global middleware layers (applied outermost = listed last)
            for mw in &global_mw {
                e.writeln(&format!(
                    ".layer(axum::middleware::from_fn({}))",
                    mw.handler_path
                ));
            }

            e.dedent();
        }
    });

    e.finish()
}

/// Generate the `src/gale_ssr.rs` SSR runtime helper module.
///
/// Provides HTML escaping and other utilities needed by generated SSR code.
pub fn generate_gale_ssr_runtime() -> String {
    let mut e = RustEmitter::new();
    e.emit_file_header("SSR runtime helpers.");
    e.newline();

    e.emit_doc_comment("Escape a string for safe embedding in HTML content.");
    e.emit_fn(
        "pub",
        false,
        "escape_html",
        &[("s", "&str")],
        Some("String"),
        |e| {
            e.writeln("s.replace('&', \"&amp;\")");
            e.indent();
            e.writeln(".replace('<', \"&lt;\")");
            e.writeln(".replace('>', \"&gt;\")");
            e.writeln(".replace('\"', \"&quot;\")");
            e.writeln(".replace('\\'', \"&#39;\")");
            e.dedent();
        },
    );

    e.finish()
}

/// Generate the `src/gale_middleware.rs` middleware runtime helper module.
///
/// Provides `GaleRequest` and `GaleResponse` wrapper types for use in
/// GaleX-generated middleware functions.
pub fn generate_gale_middleware_runtime() -> String {
    let mut e = RustEmitter::new();
    e.emit_file_header("Middleware runtime helpers.");
    e.newline();

    e.emit_use("axum::body::Body");
    e.emit_use("axum::http::{Request, HeaderValue, StatusCode}");
    e.emit_use("axum::response::{IntoResponse, Response}");
    e.newline();

    // GaleRequest wrapper
    e.emit_doc_comment("Wrapper around Axum Request providing GaleX convenience methods.");
    e.writeln("pub struct GaleRequest(pub Request<Body>);");
    e.newline();

    e.block("impl GaleRequest", |e| {
        e.emit_doc_comment("Get a request header value by name.");
        e.block(
            "pub fn header(&self, name: &str) -> Option<String>",
            |e| {
                e.writeln("self.0.headers().get(name)");
                e.indent();
                e.writeln(".and_then(|v| v.to_str().ok())");
                e.writeln(".map(String::from)");
                e.dedent();
            },
        );
        e.newline();

        e.emit_doc_comment("Get the HTTP method as a string.");
        e.block("pub fn method(&self) -> String", |e| {
            e.writeln("self.0.method().to_string()");
        });
        e.newline();

        e.emit_doc_comment("Get the request URI path.");
        e.block("pub fn path(&self) -> String", |e| {
            e.writeln("self.0.uri().path().to_string()");
        });
        e.newline();

        e.emit_doc_comment("Set a request header.");
        e.block(
            "pub fn set_header(&mut self, name: &str, value: &str)",
            |e| {
                e.block("if let Ok(hv) = HeaderValue::from_str(value)", |e| {
                    e.block(
                        "if let Ok(hn) = axum::http::header::HeaderName::from_bytes(name.as_bytes())",
                        |e| {
                            e.writeln("self.0.headers_mut().insert(hn, hv);");
                        },
                    );
                });
            },
        );
        e.newline();

        e.emit_doc_comment("Unwrap the inner Axum Request for passing to `next.run()`.");
        e.block("pub fn into_inner(self) -> Request<Body>", |e| {
            e.writeln("self.0");
        });
    });
    e.newline();

    // GaleResponse builder
    e.emit_doc_comment("Response builder for GaleX middleware.");
    e.writeln("pub struct GaleResponse;");
    e.newline();

    e.block("impl GaleResponse", |e| {
        e.emit_doc_comment("Create a response with the given HTTP status code.");
        e.block("pub fn status(code: u16) -> Response", |e| {
            e.writeln("StatusCode::from_u16(code)");
            e.indent();
            e.writeln(".unwrap_or(StatusCode::INTERNAL_SERVER_ERROR)");
            e.writeln(".into_response()");
            e.dedent();
        });
        e.newline();

        e.emit_doc_comment("Create a JSON response.");
        e.block("pub fn json(data: serde_json::Value) -> Response", |e| {
            e.writeln("axum::Json(data).into_response()");
        });
        e.newline();

        e.emit_doc_comment("Create a plain text response.");
        e.block("pub fn text(s: &str) -> Response", |e| {
            e.writeln("s.to_string().into_response()");
        });
        e.newline();

        e.emit_doc_comment("Create a redirect response.");
        e.block("pub fn redirect(url: &str) -> Response", |e| {
            e.writeln("axum::response::Redirect::to(url).into_response()");
        });
    });

    e.finish()
}

/// Configuration for which top-level modules to declare in main.rs.
#[derive(Debug, Clone, Default)]
pub struct MainModules {
    pub has_actions: bool,
    pub has_guards: bool,
    pub has_channels: bool,
    pub has_shared: bool,
    pub has_routes: bool,
    pub has_api: bool,
    pub has_middleware: bool,
    pub has_env: bool,
}

/// Generate a `mod.rs` that re-exports child modules.
///
/// Produces:
/// ```text
/// pub mod child1;
/// pub mod child2;
/// ```
pub fn generate_mod_rs(children: &[&str]) -> String {
    let mut e = RustEmitter::new();
    for child in children {
        e.writeln(&format!("pub mod {child};"));
    }
    e.finish()
}

/// Generate an empty placeholder module.
pub fn generate_placeholder_mod(description: &str) -> String {
    let mut e = RustEmitter::new();
    e.emit_file_header(description);
    e.finish()
}

/// Generate the `src/shared/validation.rs` module.
///
/// Provides the [`ValidationError`] struct used by all guard `validate()` methods.
pub fn generate_validation_rs() -> String {
    let mut e = RustEmitter::new();
    e.emit_file_header("Shared validation types.");
    e.newline();

    e.emit_use("serde::Serialize");
    e.newline();

    e.emit_doc_comment("A single field-level validation error.");
    e.emit_struct(
        &["derive(Debug, Clone, Serialize)"],
        "pub",
        "ValidationError",
        &[("field", "String"), ("message", "String")],
    );
    e.newline();

    e.emit_impl("ValidationError", |e| {
        e.emit_doc_comment("Create a new validation error for the given field.");
        e.emit_fn(
            "pub",
            false,
            "new",
            &[("field", "&str"), ("message", "&str")],
            Some("Self"),
            |e| {
                e.block("Self", |e| {
                    e.writeln("field: field.to_string(),");
                    e.writeln("message: message.to_string(),");
                });
            },
        );
    });
    e.newline();

    // Validate trait
    e.emit_doc_comment("Trait for types that can be validated against constraints.");
    e.block("pub trait Validate", |e| {
        e.emit_doc_comment("Check all constraints and return any validation errors.");
        e.writeln("fn validate(&self) -> Result<(), Vec<ValidationError>>;");
    });
    e.newline();

    // Sanitize trait
    e.emit_doc_comment("Trait for types that have input transforms (trim, precision, defaults).");
    e.block("pub trait Sanitize", |e| {
        e.emit_doc_comment("Apply transforms to the input in place before validation.");
        e.writeln("fn sanitize(&mut self);");
    });

    e.finish()
}

// ── Scaffold builder ───────────────────────────────────────────────────

/// Generate the full project scaffold (Cargo.toml + src/main.rs + directory stubs).
///
/// This produces the minimum viable project structure. Later codegen
/// phases populate the `actions/`, `guards/`, `channels/`, `routes/`,
/// and `shared/` directories with actual generated code.
pub fn scaffold(project_name: &str) -> ProjectFiles {
    let mut files = ProjectFiles::new();

    // Cargo.toml
    // scaffold() is only used in tests; real builds go through CodegenContext
    // which resolves the dep at runtime via resolve_gale_dep().
    files.add_file(
        "Cargo.toml",
        generate_cargo_toml(project_name, false, "\"0.0.0\""),
    );

    // src/main.rs — start with all modules disabled; they'll be enabled
    // once CodegenContext populates them.
    let modules = MainModules::default();
    files.add_file(
        "src/main.rs",
        generate_main_rs(&modules, false, &[], &[], &[], &[], &[]),
    );

    files
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_toml_has_package_name() {
        let toml = generate_cargo_toml("my_app", false, "\"0.0.0\"");
        assert!(toml.contains("name = \"my_app\""));
    }

    #[test]
    fn cargo_toml_has_gale_dep_path() {
        let toml = generate_cargo_toml("test", false, "{ path = \"/usr/local/lib/gale\" }");
        assert!(toml.contains("gale = { path = \"/usr/local/lib/gale\" }"));
    }

    #[test]
    fn cargo_toml_has_gale_dep_git() {
        let toml = generate_cargo_toml(
            "test",
            false,
            "{ git = \"https://github.com/m-de-graaff/Gale\", tag = \"v0.1.4\" }",
        );
        assert!(toml.contains("gale = { git ="));
        assert!(toml.contains("tag = \"v0.1.4\""));
    }

    #[test]
    fn cargo_toml_has_axum_dep() {
        let toml = generate_cargo_toml("test", false, "\"0.0.0\"");
        assert!(toml.contains("axum = { version = \"0.8\", features = [\"ws\"] }"));
    }

    #[test]
    fn cargo_toml_has_serde_dep() {
        let toml = generate_cargo_toml("test", false, "\"0.0.0\"");
        assert!(toml.contains("serde = "));
        assert!(toml.contains("serde_json = "));
    }

    #[test]
    fn cargo_toml_has_release_profile() {
        let toml = generate_cargo_toml("test", false, "\"0.0.0\"");
        assert!(toml.contains("[profile.release]"));
        assert!(toml.contains("lto = true"));
    }

    #[test]
    fn main_rs_has_tokio_main() {
        let main = generate_main_rs(&MainModules::default(), false, &[], &[], &[], &[], &[]);
        assert!(main.contains("#[tokio::main]"));
        assert!(main.contains("async fn main()"));
    }

    #[test]
    fn main_rs_has_config_load() {
        let main = generate_main_rs(&MainModules::default(), false, &[], &[], &[], &[], &[]);
        assert!(main.contains("Config::load()"));
    }

    #[test]
    fn main_rs_has_build_router() {
        let main = generate_main_rs(&MainModules::default(), false, &[], &[], &[], &[], &[]);
        assert!(main.contains("fn build_router()"));
        assert!(main.contains("axum::Router::new()"));
    }

    #[test]
    fn main_rs_declares_modules_when_present() {
        let modules = MainModules {
            has_actions: true,
            has_guards: true,
            has_channels: false,
            has_shared: true,
            has_routes: false,
            has_api: false,
            has_middleware: false,
            has_env: false,
        };
        let main = generate_main_rs(&modules, false, &[], &[], &[], &[], &[]);
        assert!(main.contains("mod actions;"));
        assert!(main.contains("mod guards;"));
        assert!(!main.contains("mod channels;"));
        assert!(main.contains("mod shared;"));
        assert!(!main.contains("mod routes;"));
    }

    #[test]
    fn main_rs_has_file_header() {
        let main = generate_main_rs(&MainModules::default(), false, &[], &[], &[], &[], &[]);
        assert!(main.contains("Generated by GaleX compiler"));
    }

    #[test]
    fn generate_mod_rs_lists_children() {
        let modrs = generate_mod_rs(&["create_user", "login"]);
        assert!(modrs.contains("pub mod create_user;"));
        assert!(modrs.contains("pub mod login;"));
    }

    #[test]
    fn scaffold_produces_expected_files() {
        let files = scaffold("test_app");
        assert!(files.contains("Cargo.toml"));
        assert!(files.contains("src/main.rs"));
    }

    #[test]
    fn scaffold_cargo_toml_uses_project_name() {
        let files = scaffold("my_project");
        let toml = files.get("Cargo.toml").unwrap();
        assert!(toml.contains("name = \"my_project\""));
    }

    #[test]
    fn project_files_len_and_empty() {
        let mut files = ProjectFiles::new();
        assert!(files.is_empty());
        assert_eq!(files.len(), 0);
        files.add_file("test.rs", "// test".into());
        assert!(!files.is_empty());
        assert_eq!(files.len(), 1);
    }

    #[test]
    fn project_files_get() {
        let mut files = ProjectFiles::new();
        files.add_file("src/lib.rs", "pub mod foo;".into());
        assert_eq!(files.get("src/lib.rs"), Some("pub mod foo;"));
        assert_eq!(files.get("nonexistent"), None);
    }

    #[test]
    fn cargo_toml_has_ws_feature() {
        let toml = generate_cargo_toml("test", false, "\"0.0.0\"");
        assert!(toml.contains("features = [\"ws\"]"));
    }

    #[test]
    fn main_rs_has_channel_routes() {
        let modules = MainModules {
            has_channels: true,
            ..MainModules::default()
        };
        let channel_routes = vec![("Chat".to_string(), "chat".to_string())];
        let main = generate_main_rs(&modules, false, &[], &[], &[], &channel_routes, &[]);
        assert!(main.contains("mod channels;"));
        assert!(main.contains("/ws/__gx/channels/Chat"));
        assert!(main.contains("channels::chat::handler"));
        assert!(main.contains("ChatState::new()"));
    }
}
